package needbook;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.*;
import javax.swing.table.*;;

/**
 *
 * @author Lenovo
 */
public class buku_dipinjam extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    ResultSet RsSiswa = null;
    int idSiswa;
    /**
     * Creates new form buku_dipinjam
     */
    public buku_dipinjam(int idSiswa) {
        initComponents();
        this.idSiswa = idSiswa;
        tampilData();
        System.out.println(idSiswa);
    }
    
    private boolean checkAdminRights(int idSiswa) {
        boolean isAdmin = false;
        try {
            Connection conn = koneksi.koneksiDB();
            PreparedStatement stmt = conn.prepareStatement("SELECT is_admin FROM user WHERE id = ?");
            stmt.setInt(1, idSiswa);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                isAdmin = rs.getBoolean("is_admin");
            }
        } catch (SQLException ex) {
            System.err.println("Error: " + ex);
        }
        return isAdmin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_buku = new javax.swing.JTable();
        btn_dipinjam = new javax.swing.JButton();
        btn_dashboard = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setForeground(new java.awt.Color(255, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 1080));

        table_buku.setBackground(new java.awt.Color(51, 51, 51));
        table_buku.setForeground(new java.awt.Color(255, 255, 255));
        table_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "KODE_BUKU", "JUDUL", "PENGARANG", "KATEGORI"
            }
        ));
        table_buku.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jScrollPane2.setViewportView(table_buku);

        btn_dipinjam.setBackground(new java.awt.Color(0, 0, 0));
        btn_dipinjam.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_dipinjam.setForeground(new java.awt.Color(255, 255, 255));
        btn_dipinjam.setText("LIST PINJAMAN");
        btn_dipinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dipinjamActionPerformed(evt);
            }
        });

        btn_dashboard.setBackground(new java.awt.Color(0, 0, 0));
        btn_dashboard.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_dashboard.setText("DASHBOARD");
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Asus Rog", 1, 48)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title.setText("NeedBook");

        back_btn.setBackground(new java.awt.Color(0, 0, 0));
        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setText("BACK");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1960, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(btn_dipinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dipinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 658, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 3343, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dipinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dipinjamActionPerformed
        buku_dipinjam bukuDipinjamFrame = new buku_dipinjam(idSiswa);
        bukuDipinjamFrame.setVisible(true); // Menampilkan jendela buku_dipinjam
        this.dispose();
    }//GEN-LAST:event_btn_dipinjamActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        admin_page bukuDipinjamFrame = new admin_page();
        bukuDipinjamFrame.setVisible(true); // Menampilkan jendela buku_dipinjam
        this.dispose();
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        pinjam_buku frametambah_data = new pinjam_buku(idSiswa);
        frametambah_data.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

     private void tampilData() {
        try {
            Object[] judul_kolom = {"ID", "NAMA_SISWA", "JUDUL_BUKU"};
            tableModel = new DefaultTableModel(null, judul_kolom);
            table_buku.setModel(tableModel);

            Connection conn = koneksi.koneksiDB();
            Statement stt = conn.createStatement();
            tableModel.getDataVector().removeAllElements();

            boolean isAdmin = checkAdminRights(idSiswa);
            String query;
            if (isAdmin) {
                query = "SELECT p.id AS id, s.username AS siswa, b.judul AS buku FROM peminjaman p JOIN siswa s ON p.siswa_id = s.id JOIN buku b ON p.book_id = b.id;";
            } else {
                query = "SELECT p.id AS id, s.username AS siswa, b.judul AS buku FROM peminjaman p JOIN siswa s ON p.siswa_id = s.id JOIN buku b ON p.book_id = b.id WHERE p.siswa_id = " + idSiswa + ";";
            }

            RsSiswa = stt.executeQuery(query);
            while (RsSiswa.next()) {
                Object[] data = {
                        RsSiswa.getString("id"),
                        RsSiswa.getString("siswa"),
                        RsSiswa.getString("buku")
                };
                tableModel.addRow(data);
            }

            TableColumnModel columnModel = table_buku.getColumnModel();
            TableColumn kodeBukuColumn = columnModel.getColumn(0);
            kodeBukuColumn.setMinWidth(0);
            kodeBukuColumn.setMaxWidth(0);
            kodeBukuColumn.setPreferredWidth(0);

        } catch (Exception ex) {
            System.err.println("error" + ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
//     public static void main(String args[]) {
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(buku_dipinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//
//        java.awt.EventQueue.invokeLater(() -> {
//            new buku_dipinjam(6).setVisible(true);
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_dipinjam;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_buku;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
