package needbook;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author Lenovo
 */
public class pinjam_buku extends javax.swing.JFrame {
    DefaultTableModel tableModel;
    ResultSet RsSiswa = null;
    int idSiswa;
    boolean isAdmin = false;

    /**
     * Creates new form pinjam_buku
     * @param idSiswa
     */
    public pinjam_buku(int idSiswa) {
        initComponents();
        tampilData();
        this.idSiswa = idSiswa;
        checkAdminStatus(idSiswa); // Panggil fungsi untuk memeriksa status admin saat inisialisasi
    }
    
    private void checkAdminStatus(int id) {
        try {
            Connection conn = (Connection) koneksi.koneksiDB();
            Statement stt = conn.createStatement();
            ResultSet rs = stt.executeQuery("SELECT is_admin FROM siswa WHERE id = " + id);

            if (rs.next()) {
                isAdmin = rs.getBoolean("is_admin");
                btn_dipinjam.setVisible(isAdmin); // Atur visibilitas tombol berdasarkan status admin
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Gagal memeriksa status admin.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_buku = new javax.swing.JTable();
        btn_dipinjam = new javax.swing.JButton();
        btn_dashboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        title.setFont(new java.awt.Font("Asus Rog", 1, 48)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        title.setText("NeedBook");

        table_buku.setBackground(new java.awt.Color(51, 51, 51));
        table_buku.setForeground(new java.awt.Color(255, 255, 255));
        table_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "KODE_BUKU", "JUDUL", "PENGARANG", "KATEGORI"
            }
        ));
        table_buku.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jScrollPane2.setViewportView(table_buku);

        btn_dipinjam.setBackground(new java.awt.Color(0, 0, 0));
        btn_dipinjam.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_dipinjam.setForeground(new java.awt.Color(255, 255, 255));
        btn_dipinjam.setText("LIST PINJAMAN");
        btn_dipinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dipinjamActionPerformed(evt);
            }
        });

        btn_dashboard.setBackground(new java.awt.Color(0, 0, 0));
        btn_dashboard.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        btn_dashboard.setText("DASHBOARD");
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 1039, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_dipinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(232, 232, 232))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dipinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(471, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dipinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dipinjamActionPerformed
        buku_dipinjam bukuDipinjamFrame = new buku_dipinjam(idSiswa);
        bukuDipinjamFrame.setVisible(true); // Menampilkan jendela buku_dipinjam
        this.dispose();
    }//GEN-LAST:event_btn_dipinjamActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        admin_page bukuDipinjamFrame = new admin_page();
        bukuDipinjamFrame.setVisible(true); // Menampilkan jendela buku_dipinjam
        this.dispose();
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void tampilData() {
        try{
            Object[] judul_kolom = {"KODE-BUKU", "JUDUL", "PENGARANG", "KATEGORI"};
            tableModel = new DefaultTableModel(null, judul_kolom);
            table_buku.setModel(tableModel);

            Connection conn = (Connection) koneksi.koneksiDB();
            Statement stt = conn.createStatement();
            tableModel.getDataVector().removeAllElements();

            RsSiswa = stt.executeQuery("SELECT * FROM buku");
            while(RsSiswa.next()){
                Object[] data = {
                    RsSiswa.getString("id"),
                    RsSiswa.getString("judul"),
                    RsSiswa.getString("pengarang"),
                    RsSiswa.getString("kategori")
                };
                tableModel.addRow(data);
            }

            // Mengambil objek TableColumnModel dari tabel
            TableColumnModel columnModel = table_buku.getColumnModel();
            // Mengambil kolom pertama (indeks 0), yang merupakan kolom ID
            TableColumn kodeBukuColumn = columnModel.getColumn(0);
            // Mengatur lebar kolom ID menjadi 0 sehingga tidak terlihat di tabel
            kodeBukuColumn.setMinWidth(0);
            kodeBukuColumn.setMaxWidth(0);
            kodeBukuColumn.setPreferredWidth(0);

        }catch(Exception ex){
            System.err.println("error" + ex);
        }
    }

    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(pinjam_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(pinjam_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(pinjam_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(pinjam_buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new pinjam_buku(0).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_dipinjam;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_buku;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
